[build]
  python = "3.11"
  
[build]
  buildCommand = "apt-get update && apt-get install -y python3-pip && python3 -m pip install -r requirements.txt"

[start]
  startCommand = "uv run python3 main.py"


